---
- name: Deploy Docker container and manage Nginx with SSL
  hosts: node2
  become: true
  vars:
    external_port: "{{ external_port }}"
    internal_port: "{{ internal_port }}"
    docker_image: "{{ docker_image }}"
    container_name: "{{ container_name }}"
    domain_name: "{{ domain_name }}"
    app_port: "{{ external_port }}"
  tasks:
    - name: Check if a container with the same name is already running
      command: docker ps -q --filter "name={{ container_name }}"
      register: existing_container
      changed_when: false

    - name: Stop the existing container if it is running
      when: existing_container.stdout != ""
      command: docker stop "{{ existing_container.stdout }}"
      ignore_errors: yes

    - name: Remove the existing container if it exists
      command: docker rm -f "{{ container_name }}"
      ignore_errors: yes

    - name: Deploy new container
      command: docker run -d --name "{{ container_name }}" -p "{{ external_port }}:{{ internal_port }}" "{{ docker_image }}"
      register: deploy_result
      failed_when: deploy_result.rc != 0

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install Certbot and Nginx plugin
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Setup Nginx Server Block
      template:
        src: nginx_domain.conf.j2
        dest: "/etc/nginx/sites-available/{{ domain_name }}"

    - name: Enable Nginx configuration
      file:
        src: "/etc/nginx/sites-available/{{ domain_name }}"
        dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
        state: link

    - name: Reload Nginx to apply changes
      service:
        name: nginx
        state: reloaded

    - name: Obtain and Install SSL Certificate with Certbot
      command: certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos -m your@email.com --redirect
      args:
        creates: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
