- name: Deploy Docker container and manage Nginx with SSL
  hosts: node2
  become: true
  vars:
    external_port: "{{ external_port }}"
    internal_port: "{{ internal_port }}"
    docker_image: "{{ docker_image }}"
    container_name: "{{ container_name }}"
    domain_name: "{{ domain_name }}"
    app_port: "{{ external_port }}"

  tasks:
    - name: Check if the container is running
      command: docker ps -q -f name={{ container_name }}
      register: container_id
      changed_when: false

    - name: Stop and remove existing container if it exists
      docker_container:
        name: "{{ container_name }}"
        state: absent
      when: container_id.stdout != ""

    - name: Deploy with docker
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        published_ports:
          - "{{ external_port }}:{{ internal_port }}"

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Setup Nginx Server Block
      template:
        src: nginx_domain.conf.j2
        dest: "/etc/nginx/sites-available/{{ domain_name }}"

    - name: Enable Nginx configuration
      file:
        src: "/etc/nginx/sites-available/{{ domain_name }}"
        dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
        state: link

    - name: Reload Nginx to apply changes
      service:
        name: nginx
        state: reloaded
    - name: Obtain and Install SSL Certificate with Certbot
      command: sudo certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos -m pisethsattya33@email.com --redirect
      args:
        creates: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
      register: certbot_result
      notify:
        - Reload Nginx

  handlers:
      - name: Reload Nginx
        service:
          name: nginx
          state: reloaded