---
- name: Deploy Docker container and manage Nginx with SSL
  hosts: node2
  become: true
  vars:
    external_port: "{{ external_port }}"
    internal_port: "{{ internal_port }}"
    docker_image: "{{ docker_image }}"
    container_name: "{{ container_name }}"
    domain_name: "{{ domain_name }}"
    app_port: "{{ external_port }}"
    email: "pisethsattya33@email.com"  # Certbot email
    nginx_conf_path: "/etc/nginx/sites-available/{{ domain_name }}"
    ssl_cert_path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"

  tasks:
    - name: Check if the container is running
      shell: docker ps -q -f name={{ container_name }}
      register: container_id
      changed_when: false

    - name: Stop and remove existing container if it exists
      docker_container:
        name: "{{ container_name }}"
        state: absent
      when: container_id.stdout != ""

    - name: Deploy Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        published_ports:
          - "{{ external_port }}:{{ internal_port }}"
        restart_policy: always

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx service is running
      service:
        name: nginx
        state: started
        enabled: true

    - name: Set up Nginx server block
      template:
        src: nginx_domain.conf.j2
        dest: "{{ nginx_conf_path }}"
      notify: 
        - Reload Nginx

    - name: Enable Nginx site
      file:
        src: "{{ nginx_conf_path }}"
        dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
        state: link
      notify:
        - Reload Nginx

    - name: Obtain SSL certificate with Certbot
      command: >
        certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos
        -m {{ email }} --redirect
      args:
        creates: "{{ ssl_cert_path }}"
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
