---
- name: Ensure Docker is installed and configured
  hosts: all
  become: yes
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_version
      ignore_errors: yes

    - name: Install prerequisites for Docker installation
      when: docker_version.failed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker’s official GPG key
      when: docker_version.failed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      when: docker_version.failed
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
        state: present

    - name: Install Docker Engine
      when: docker_version.failed
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker is started and enabled
      when: docker_version.failed
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure user is added to the Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Ensure Docker socket permissions are correct
      file:
        path: /var/run/docker.sock
        owner: root
        group: docker
        mode: '0660'
        state: file

    - name: Notify user to log out and log back in
      debug:
        msg: "Please log out and log back in to apply group membership changes."

    - name: Verify Docker installation
      command: docker --version
      register: docker_installed
      changed_when: false

    - name: Output Docker version
      debug:
        msg: "Docker installed: {{ docker_installed.stdout }}"
