---
- name: Ensure Docker is installed on Ubuntu 22.04 LTS
  hosts: all
  become: yes
  vars:
    docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"

  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_version
      ignore_errors: yes

    - name: Install prerequisites for Docker installation
      when: docker_version.failed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker’s official GPG key
      when: docker_version.failed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      when: docker_version.failed
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: Install Docker Engine
      when: docker_version.failed
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker is started and enabled
      when: docker_version.failed
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      when: docker_version.failed
      command: docker --version
      register: docker_installed
      changed_when: false

    - name: Output Docker version
      when: docker_version.failed
      debug:
        msg: "Docker installed: {{ docker_installed.stdout }}"
