---
- name: Uninstall Docker from Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Stop Docker service
      systemd:
        name: docker
        state: stopped
        enabled: no

    - name: Remove Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent

    - name: Remove Docker GPG key
      file:
        path: /usr/share/keyrings/docker-archive-keyring.gpg
        state: absent

    - name: Remove Docker repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        filename: docker
        state: absent

    - name: Remove Docker group
      group:
        name: docker
        state: absent

    - name: Remove Docker user permissions (if necessary)
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: no
