---
- name: Uninstall Docker from Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Stop Docker service
      systemd:
        name: docker
        state: stopped
        enabled: no

    - name: Remove Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent

    - name: Remove Docker GPG key
      file:
        path: /usr/share/keyrings/docker-archive-keyring.gpg
        state: absent

    - name: Remove Docker repository file
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove Docker group
      group:
        name: docker
        state: absent

    - name: Remove Docker user permissions (if necessary)
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: no
